In [1]:
import pandas as pd
import os
import json
import sys
import numpy as np
from pandas_profiling import ProfileReport

# BGG

In [2]:
with open(os.path.join(".", "data", "bgg", "bgg_inf_bizt"), "r") as json_file:
    data = json.load(json_file)

In [7]:
df = pd.read_json(os.path.join(".", "data", "bgg", "bgg_inf_bizt")).T

In [8]:
df

,bgg_rank,name,url,year,geek_rating,avg_rating,num_voters,primary name,alternate names,year published,...,artists,publishers,categories,mechanisms,family,designers,artist,publisher,category,mechanism
10000,1,Gloomhaven,https://boardgamegeek.com/boardgame/174430/glo...,2017,8.577,8.83,34705,[gloomhaven],"[gloomhaven, aventures à havrenuit, gloomhaven...",[2017],...,"[alexandr elichev, josh t. mcdowell, alvaro ne...","[cephalofair games, albi, asmodee, feuerland s...","[adventure, exploration, fantasy, fighting, mi...","[action retrieval, campaign / battle card driv...","[campaign games, components: miniatures, crowd...",NaN,NaN,NaN,NaN,NaN
10001,2,Pandemic Legacy: Season 1,https://boardgamegeek.com/boardgame/161936/pan...,2015,8.471,8.62,36835,[pandemic legacy: season 1],"[pandemic legacy: saison 1, pandemic legacy: 1...",[2015],...,NaN,"[z-man games, inc., asterion press, devir, fil...","[environmental, medical]","[action points, cooperative game, hand managem...","[campaign games, legacy, pandemic]","[rob daviau, matt leacock]",[chris quilliams],NaN,NaN,NaN
10002,3,Terraforming Mars,https://boardgamegeek.com/boardgame/167791/ter...,2016,8.277,8.43,53504,[terraforming mars],"[a mars terraformálása, mars: teraformace, ter...",[2016],...,NaN,"[fryxgames, arclight, fantasmagoria, ghenos ga...","[economic, environmental, industry / manufactu...","[card drafting, end game bonuses, hand managem...","[fryxgames' future timeline, planets: mars, so...",NaN,[isaac fryxelius],NaN,NaN,NaN
10003,4,Brass: Birmingham,https://boardgamegeek.com/boardgame/224517/bra...,2018,8.268,8.63,12591,[brass: birmingham],"[brass. бирмингем, 브라스: 버밍엄]",[2018],...,"[lina cossette, david forest, damien mammoliti]","[roxley, boardm factory, conclave editora, cro...","[economic, industry / manufacturing, transport...","[connections, hand management, income, loans, ...","[brass, cities: birmingham (england), country:...","[gavan brown, matt tolman, martin wallace]",NaN,NaN,NaN,NaN
10004,5,Through the Ages: A New Story of Civilization,https://boardgamegeek.com/boardgame/182028/thr...,2015,8.222,8.47,19822,[through the ages: a new story of civilization],"[cywilizacja: poprzez wieki, im wandel der zei...",[2015],...,"[filip murmak, radim pech, jakub politzer, mil...","[czech games edition, cranio creations, devir,...","[card game, civilization, economic]","[action points, auction/bidding, auction: dutc...","[tableau building, through the ages]",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500095,4996,Trickster: Champions of Time,https://boardgamegeek.com/boardgame/218310/tri...,2017,5.672,6.50,298,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500096,4997,Clash for a Continent: Battles of the America...,https://boardgamegeek.com/boardgame/14860/clas...,2005,5.672,7.24,170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500097,4998,Five Cucumbers,https://boardgamegeek.com/boardgame/147768/fiv...,2013,5.672,5.91,1072,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500098,4999,Just Desserts,https://boardgamegeek.com/boardgame/18946/just...,2015,5.672,6.16,602,[just desserts],"[desserts parfaits, mi postre favorito]",[2015],...,"[brooke allen, andrew heath]","[edge entertainment, looney labs]",NaN,NaN,[food / cooking],NaN,NaN,NaN,[card game],[set collection]
500099,5000,Plunder,https://boardgamegeek.com/boardgame/13347/plunder,2004,5.672,6.15,565,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#Dic size MB
sys.getsizeof(data) / (1024*2024)

0.039552711215415016

In [10]:
#DataFrame size MB
sys.getsizeof(df) / (1024*2024)

1.5813533496479744

## Basic info

In [13]:
df.head(2)

,bgg_rank,name,url,year,geek_rating,avg_rating,num_voters,primary name,alternate names,year published,...,artists,publishers,categories,mechanisms,family,designers,artist,publisher,category,mechanism
10000,1,Gloomhaven,https://boardgamegeek.com/boardgame/174430/glo...,2017,8.577,8.83,34705,[gloomhaven],"[gloomhaven, aventures à havrenuit, gloomhaven...",[2017],...,"[alexandr elichev, josh t. mcdowell, alvaro ne...","[cephalofair games, albi, asmodee, feuerland s...","[adventure, exploration, fantasy, fighting, mi...","[action retrieval, campaign / battle card driv...","[campaign games, components: miniatures, crowd...",NaN,NaN,NaN,NaN,NaN
10001,2,Pandemic Legacy: Season 1,https://boardgamegeek.com/boardgame/161936/pan...,2015,8.471,8.62,36835,[pandemic legacy: season 1],"[pandemic legacy: saison 1, pandemic legacy: 1...",[2015],...,NaN,"[z-man games, inc., asterion press, devir, fil...","[environmental, medical]","[action points, cooperative game, hand managem...","[campaign games, legacy, pandemic]","[rob daviau, matt leacock]",[chris quilliams],NaN,NaN,NaN

In [14]:
df.tail(2)

,bgg_rank,name,url,year,geek_rating,avg_rating,num_voters,primary name,alternate names,year published,...,artists,publishers,categories,mechanisms,family,designers,artist,publisher,category,mechanism
500098,4999,Just Desserts,https://boardgamegeek.com/boardgame/18946/just...,2015,5.672,6.16,602,[just desserts],"[desserts parfaits, mi postre favorito]",[2015],...,"[brooke allen, andrew heath]","[edge entertainment, looney labs]",NaN,NaN,[food / cooking],NaN,NaN,NaN,[card game],[set collection]
500099,5000,Plunder,https://boardgamegeek.com/boardgame/13347/plunder,2004,5.672,6.15,565,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
type(df['name'])

pandas.core.series.Series

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 10000 to 500099
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bgg_rank         5000 non-null   object
 1   name             5000 non-null   object
 2   url              5000 non-null   object
 3   year             4990 non-null   object
 4   geek_rating      5000 non-null   object
 5   avg_rating       5000 non-null   object
 6   num_voters       5000 non-null   object
 7   primary name     848 non-null    object
 8   alternate names  848 non-null    object
 9   year published   848 non-null    object
 10  designer         570 non-null    object
 11  artists          494 non-null    object
 12  publishers       726 non-null    object
 13  categories       727 non-null    object
 14  mechanisms       808 non-null    object
 15  family           848 non-null    object
 16  designers        278 non-null    object
 17  artist           354 non-null    object
 18  publisher        122 non-null    object
 19  category         121 non-null    object
 20  mechanism        40 non-null     object
dtypes: object(21)
memory usage: 577.2+ KB

In [18]:
df.size

105000

In [19]:
df.shape

(5000, 21)

In [20]:
df.columns

Index(['bgg_rank', 'name', 'url', 'year', 'geek_rating', 'avg_rating',
       'num_voters', 'primary name', 'alternate names', 'year published',
       'designer', 'artists', 'publishers', 'categories', 'mechanisms',
       'family', 'designers', 'artist', 'publisher', 'category', 'mechanism'],
      dtype='object')

In [21]:
df.dtypes

bgg_rank           object
name               object
url                object
year               object
geek_rating        object
avg_rating         object
num_voters         object
primary name       object
alternate names    object
year published     object
designer           object
artists            object
publishers         object
categories         object
mechanisms         object
family             object
designers          object
artist             object
publisher          object
category           object
mechanism          object
dtype: object

In [22]:
df['year']

10000     2017
10001     2015
10002     2016
10003     2018
10004     2015
          ...
500095    2017
500096    2005
500097    2013
500098    2015
500099    2004
Name: year, Length: 5000, dtype: object

In [23]:
df.year

10000     2017
10001     2015
10002     2016
10003     2018
10004     2015
          ...
500095    2017
500096    2005
500097    2013
500098    2015
500099    2004
Name: year, Length: 5000, dtype: object

In [24]:
df['year'].unique()

array(['2017', '2015', '2016', '2018', '2005', '2012', '2011', '2013',
       '2007', '2019', '2002', '2014', '2004', '2006', '2008', '2010',
       '1995', '2009', '1876', '1997', '1981', '2020', '1999', '1993',
       '1991', '-2200', '2000', '2003', '1986', '1998', '1996', '1992',
       '1964', '1982', '1979', '1985', '1980', '1994', '2001', '1475',
       '1990', '1983', '1989', '1959', '1977', '1630', '1908', '1800',
       '1850', '1984', '1988', '1810', '1987', '1971', '1978', '-3000',
       '1587', '762', '1974', '1962', '1973', nan, '1848', '1903', '1947',
       '1938', '1948', '1960', '1895', '1976', '1930', '1967', '1745',
       '1906', '1972', '1864', '1970', '1946', '1883', '400', '1975',
       '1965', '1966', '1969', '1701', '1430', '1939', '1942', '1600',
       '1904', '1963', '1932', '1909', '1968', '1780', '700', '1921',
       '1870', '1663', '1956', '1951'], dtype=object)

In [27]:
df.loc[10000, 'year']

bgg_rank                                                           1
name                                                      Gloomhaven
url                https://boardgamegeek.com/boardgame/174430/glo...
year                                                            2017
geek_rating                                                    8.577
avg_rating                                                      8.83
num_voters                                                     34705
primary name                                            [gloomhaven]
alternate names    [gloomhaven, aventures à havrenuit, gloomhaven...
year published                                                [2017]
designer                                            [isaac childres]
artists            [alexandr elichev, josh t. mcdowell, alvaro ne...
publishers         [cephalofair games, albi, asmodee, feuerland s...
categories         [adventure, exploration, fantasy, fighting, mi...
mechanisms         [action retrieval, campaign / battle card driv...
family             [campaign games, components: miniatures, crowd...
designers                                                        NaN
artist                                                           NaN
publisher                                                        NaN
category                                                         NaN
mechanism                                                        NaN
Name: 10000, dtype: object

In [30]:
df.isna().sum()

bgg_rank              0
name                  0
url                   0
year                 10
geek_rating           0
avg_rating            0
num_voters            0
primary name       4152
alternate names    4152
year published     4152
designer           4430
artists            4506
publishers         4274
categories         4273
mechanisms         4192
family             4152
designers          4722
artist             4646
publisher          4878
category           4879
mechanism          4960
dtype: int64

## Select, slice, filter

In [31]:
df[['name', 'year']]

                                                     name  year
10000                                          Gloomhaven  2017
10001                           Pandemic Legacy: Season 1  2015
10002                                   Terraforming Mars  2016
10003                                   Brass: Birmingham  2018
10004       Through the Ages: A New Story of Civilization  2015
...                                                   ...   ...
500095                       Trickster: Champions of Time  2017
500096  Clash for a Continent:  Battles of the America...  2005
500097                                     Five Cucumbers  2013
500098                                      Just Desserts  2015
500099                                            Plunder  2004

[5000 rows x 2 columns]

In [32]:
df.loc[10000, 'name']

'Gloomhaven'

In [33]:
df.loc[10000, ['name', 'year']]

name    Gloomhaven
year          2017
Name: 10000, dtype: object

In [34]:
df.loc[:, ['name', 'year']]

                                                     name  year
10000                                          Gloomhaven  2017
10001                           Pandemic Legacy: Season 1  2015
10002                                   Terraforming Mars  2016
10003                                   Brass: Birmingham  2018
10004       Through the Ages: A New Story of Civilization  2015
...                                                   ...   ...
500095                       Trickster: Champions of Time  2017
500096  Clash for a Continent:  Battles of the America...  2005
500097                                     Five Cucumbers  2013
500098                                      Just Desserts  2015
500099                                            Plunder  2004

[5000 rows x 2 columns]

In [35]:
df.iloc[1, 1]

'Pandemic Legacy: Season 1'

In [36]:
proba = pd.DataFrame([{"a":2, "b":4}])
proba

   a  b
0  2  4

In [37]:
proba.loc[1] = [5,10]
proba

   a   b
0  2   4
1  5  10

In [38]:
proba.loc[2] = {"a": 15, "b":9}
proba

    a   b
0   2   4
1   5  10
2  15   9

In [41]:
df.columns

Index(['bgg_rank', 'name', 'url', 'year', 'geek_rating', 'avg_rating',
       'num_voters', 'primary name', 'alternate names', 'year published',
       'designer', 'artists', 'publishers', 'categories', 'mechanisms',
       'family', 'designers', 'artist', 'publisher', 'category', 'mechanism',
       'asd'],
      dtype='object')

In [40]:
df['asd'] = True

In [43]:
df['bgg_rank'] > 10

TypeError: '>' not supported between instances of 'str' and 'int'

In [44]:
df['bgg_rank'].unique()

array(['1', '2', '3', ..., '4998', '4999', '5000'], dtype=object)

In [45]:
df['bgg_rank'] = df['bgg_rank'].astype(int)

In [47]:
df['bgg_rank'] > 10

10000     False
10001     False
10002     False
10003     False
10004     False
          ...
500095     True
500096     True
500097     True
500098     True
500099     True
Name: bgg_rank, Length: 5000, dtype: bool

In [49]:
df[(df['bgg_rank'] > 100)]

,bgg_rank,name,url,year,geek_rating,avg_rating,num_voters,primary name,alternate names,year published,...,publishers,categories,mechanisms,family,designers,artist,publisher,category,mechanism,asd
20000,101,Star Realms,https://boardgamegeek.com/boardgame/147020/sta...,2014,7.455,7.59,32940,[star realms],"[звездные империи, 星域奇航]",[2014],...,"[white wizard games, adc blackfire entertainme...","[card game, fighting, science fiction]","[card drafting, deck, bag, and pool building, ...","[crowdfunding: kickstarter, star realms]","[robert dougherty, darwin kastle]",[vito gesualdi],NaN,NaN,NaN,True
20001,102,Inis,https://boardgamegeek.com/boardgame/155821/inis,2016,7.454,7.79,10817,[inis],"[иниш, イニシュ, 翠嶼秘境 inis, 이니스]",[2016],...,"[matagot, gen-x games, hobby japan, lavka game...","[card game, miniatures, mythology]","[action drafting, area majority / influence, a...","[components: miniatures, country: ireland]",NaN,NaN,NaN,NaN,NaN,True
20002,103,Legendary Encounters: An Alien Deck Building Game,https://boardgamegeek.com/boardgame/146652/leg...,2014,7.453,7.78,10378,[legendary encounters: an alien deck building ...,[],[2014],...,NaN,"[card game, fighting, horror, movies / tv / ra...","[card drafting, cooperative game, deck, bag, a...","[creatures: aliens, legendary, solitaire games]","[ben cichoski, daniel mandel]",[n/a],[upper deck entertainment],NaN,NaN,True
20003,104,T.I.M.E Stories,https://boardgamegeek.com/boardgame/146508/tim...,2015,7.447,7.63,21958,[t.i.m.e stories],"[t.i.meストーリーズ, time stories, агентство «время»...",[2015],...,"[space cowboys, adc blackfire entertainment, a...","[adventure, mature / adult, puzzle, science fi...","[cooperative game, dice rolling, storytelling,...","[t.i.m.e stories, t.i.m.e stories: white cycle...","[peggy chassenet, manuel rozoy]",NaN,NaN,NaN,NaN,True
20004,105,Decrypto,https://boardgamegeek.com/boardgame/225694/dec...,2018,7.446,7.79,8899,[decrypto],"[kódfejtő, декодер, декрипто, 截碼戰, 디크립토 -]",[2018],...,"[le scorpion masqué, 2 pionki, adc blackfire e...","[deduction, party game, spies/secret agents, w...","[communication limits, targeted clues, team-ba...",[n/a],NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500095,4996,Trickster: Champions of Time,https://boardgamegeek.com/boardgame/218310/tri...,2017,5.672,6.50,298,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
500096,4997,Clash for a Continent: Battles of the America...,https://boardgamegeek.com/boardgame/14860/clas...,2005,5.672,7.24,170,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
500097,4998,Five Cucumbers,https://boardgamegeek.com/boardgame/147768/fiv...,2013,5.672,5.91,1072,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
500098,4999,Just Desserts,https://boardgamegeek.com/boardgame/18946/just...,2015,5.672,6.16,602,[just desserts],"[desserts parfaits, mi postre favorito]",[2015],...,"[edge entertainment, looney labs]",NaN,NaN,[food / cooking],NaN,NaN,NaN,[card game],[set collection],True
500099,5000,Plunder,https://boardgamegeek.com/boardgame/13347/plunder,2004,5.672,6.15,565,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [50]:
df.loc[:,["year","geek_rating", "avg_rating", "num_voters"]] = df.loc[:,["year","geek_rating", "avg_rating", "num_voters"]].astype(float)

In [51]:
df.dtypes

bgg_rank             int32
name                object
url                 object
year               float64
geek_rating        float64
avg_rating         float64
num_voters         float64
primary name        object
alternate names     object
year published      object
designer            object
artists             object
publishers          object
categories          object
mechanisms          object
family              object
designers           object
artist              object
publisher           object
category            object
mechanism           object
asd                   bool
dtype: object

In [52]:
df[(df['geek_rating'] > 7) & (df['num_voters'] > 10000)]

,bgg_rank,name,url,year,geek_rating,avg_rating,num_voters,primary name,alternate names,year published,...,publishers,categories,mechanisms,family,designers,artist,publisher,category,mechanism,asd
10000,1,Gloomhaven,https://boardgamegeek.com/boardgame/174430/glo...,2017.0,8.577,8.83,34705.0,[gloomhaven],"[gloomhaven, aventures à havrenuit, gloomhaven...",[2017],...,"[cephalofair games, albi, asmodee, feuerland s...","[adventure, exploration, fantasy, fighting, mi...","[action retrieval, campaign / battle card driv...","[campaign games, components: miniatures, crowd...",NaN,NaN,NaN,NaN,NaN,True
10001,2,Pandemic Legacy: Season 1,https://boardgamegeek.com/boardgame/161936/pan...,2015.0,8.471,8.62,36835.0,[pandemic legacy: season 1],"[pandemic legacy: saison 1, pandemic legacy: 1...",[2015],...,"[z-man games, inc., asterion press, devir, fil...","[environmental, medical]","[action points, cooperative game, hand managem...","[campaign games, legacy, pandemic]","[rob daviau, matt leacock]",[chris quilliams],NaN,NaN,NaN,True
10002,3,Terraforming Mars,https://boardgamegeek.com/boardgame/167791/ter...,2016.0,8.277,8.43,53504.0,[terraforming mars],"[a mars terraformálása, mars: teraformace, ter...",[2016],...,"[fryxgames, arclight, fantasmagoria, ghenos ga...","[economic, environmental, industry / manufactu...","[card drafting, end game bonuses, hand managem...","[fryxgames' future timeline, planets: mars, so...",NaN,[isaac fryxelius],NaN,NaN,NaN,True
10003,4,Brass: Birmingham,https://boardgamegeek.com/boardgame/224517/bra...,2018.0,8.268,8.63,12591.0,[brass: birmingham],"[brass. бирмингем, 브라스: 버밍엄]",[2018],...,"[roxley, boardm factory, conclave editora, cro...","[economic, industry / manufacturing, transport...","[connections, hand management, income, loans, ...","[brass, cities: birmingham (england), country:...","[gavan brown, matt tolman, martin wallace]",NaN,NaN,NaN,NaN,True
10004,5,Through the Ages: A New Story of Civilization,https://boardgamegeek.com/boardgame/182028/thr...,2015.0,8.222,8.47,19822.0,[through the ages: a new story of civilization],"[cywilizacja: poprzez wieki, im wandel der zei...",[2015],...,"[czech games edition, cranio creations, devir,...","[card game, civilization, economic]","[action points, auction/bidding, auction: dutc...","[tableau building, through the ages]",NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40055,356,Hanabi,https://boardgamegeek.com/boardgame/98778/hanabi,2010.0,7.018,7.11,35795.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
40061,362,Colt Express,https://boardgamegeek.com/boardgame/158899/col...,2014.0,7.010,7.15,22033.0,[colt express],"[colt express η ληστεία του τραίνου, колт експ...",[2014],...,"[ludonaute, asmodee, asterion press, broadway ...","[american west, fighting, trains]","[action queue, hand management, memory, progra...","[colt express, components: 3-dimensional (3d)]",NaN,NaN,NaN,NaN,NaN,True
40067,368,Catan,https://boardgamegeek.com/boardgame/13/catan,1995.0,7.004,7.17,93985.0,[catan],"[catan, catan (колонизаторы), catan telepesei,...",[1995],...,"[kosmos, 999 games, albi, astrel games, bergsa...","[economic, negotiation]","[dice rolling, hexagon grid, income, modular b...","[catan, promotional board games]",NaN,NaN,NaN,NaN,NaN,True
40069,370,The Grizzled,https://boardgamegeek.com/boardgame/171668/gri...,2015.0,7.003,7.22,11237.0,[the grizzled],"[los inseparables, les poilus, remény hadművel...",[2015],...,"[sweet games, boardm factory, cmon limited, co...","[card game, world war i]","[communication limits, cooperative game, hand ...",[the grizzled],"[fabien riffaud, juan rodriguez]",[tignous],NaN,NaN,NaN,True
40070,371,Legends of Andor,https://boardgamegeek.com/boardgame/127398/leg...,2012.0,7.001,7.22,13494.0,[legends of andor],"[andor, andor legendái, andor: dobrodružné leg...",[2012],...,"[kosmos, 999 games, albi, arclight, devir, fan...","[adventure, fantasy, fighting, puzzle]","[area movement, cooperative game, dice rolling...",[legends of andor],NaN,NaN,NaN,NaN,NaN,True

## Change DataFrame

In [55]:
df.columns

Index(['bgg_rank', 'name', 'year', 'geek_rating', 'avg_rating', 'num_voters',
       'designer', 'artists', 'publishers', 'categories', 'mechanisms',
       'family', 'designers', 'artist', 'publisher', 'category', 'mechanism',
       'asd'],
      dtype='object')

In [54]:
df.drop(['url', 'primary name', 'alternate names', 'year published'], axis=1, inplace = True)

In [56]:
df['boardgame'] = True

In [57]:
df['success'] = False
df.loc[df['geek_rating'] > 6, 'success'] = True

In [60]:
df.groupby(['success'])['geek_rating'].count()

success
False    2683
True     2317
Name: geek_rating, dtype: int64

In [61]:
df.groupby(['year', 'success'])['geek_rating'].count().tail(16)

year    success
2013.0  False      126
        True       132
2014.0  False      148
        True       145
2015.0  False      186
        True       182
2016.0  False      189
        True       190
2017.0  False      217
        True       213
2018.0  False      227
        True       177
2019.0  False      214
        True       130
2020.0  False       15
        True         6
Name: geek_rating, dtype: int64

In [62]:
df['geek_rating']

10000     8.577
10001     8.471
10002     8.277
10003     8.268
10004     8.222
          ...
500095    5.672
500096    5.672
500097    5.672
500098    5.672
500099    5.672
Name: geek_rating, Length: 5000, dtype: float64

In [63]:
df['num_voters']

10000     34705.0
10001     36835.0
10002     53504.0
10003     12591.0
10004     19822.0
           ...
500095      298.0
500096      170.0
500097     1072.0
500098      602.0
500099      565.0
Name: num_voters, Length: 5000, dtype: float64

In [64]:
df['num_voters'] * df['geek_rating']

10000     297664.785
10001     312029.285
10002     442852.608
10003     104102.388
10004     162976.484
             ...
500095      1690.256
500096       964.240
500097      6080.384
500098      3414.544
500099      3204.680
Length: 5000, dtype: float64

In [65]:
df['categories'].isnull().sum()

4273

In [67]:
df['categories'] = df['categories'].where(df['categories'].notnull(), df['category'])

In [68]:
df['categories'].isnull().sum()

4152

In [69]:
df.columns

Index(['bgg_rank', 'name', 'year', 'geek_rating', 'avg_rating', 'num_voters',
       'designer', 'artists', 'publishers', 'categories', 'mechanisms',
       'family', 'designers', 'artist', 'publisher', 'category', 'mechanism',
       'asd', 'boardgame', 'success'],
      dtype='object')

In [70]:
df['publishers'] = df['publishers'].where(df['publishers'].notnull(), df['publisher'])
df['mechanisms'] = df['mechanisms'].where(df['mechanisms'].notnull(), df['mechanism'])
df['designers'] = df['designers'].where(df['designers'].notnull(), df['designer'])
df['artists'] = df['artists'].where(df['artists'].notnull(), df['artist'])

In [71]:
df.drop(['category', 'publisher', 'mechanism', 'designer', 'artist'], axis=1, inplace = True)

In [72]:
df.columns

Index(['bgg_rank', 'name', 'year', 'geek_rating', 'avg_rating', 'num_voters',
       'artists', 'publishers', 'categories', 'mechanisms', 'family',
       'designers', 'asd', 'boardgame', 'success'],
      dtype='object')

## Apply

In [ ]:
for index, row in df.iterrows():
    if isinstance(row['categories'], list):
        for cat in row['categories']:
            if cat in df.columns:
                df.loc[index, cat] = True

            else:
                df[cat] = False
                df.loc[index, cat] = True

In [ ]:
df.columns

In [ ]:
df.groupby(['year'])['fantasy'].sum()

In [ ]:
df['num_voters'].apply(lambda x: x**0.5)

In [ ]:
def fun(rating): 
  
    if rating<6: 
        return "ehhh"
  
    elif rating>= 6 and rating<8: 
        return "mehhh"
  
    else: 
        return "uhhh"

In [ ]:
df['s_suc'] = df['avg_rating'].apply(fun)

In [ ]:
df.groupby(['year', 's_suc'])['fantasy'].count().tail(16)

## Pandas Profiling

In [ ]:
profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}})
profile.to_file("report.html")